### command for running python script with faulthandler for better logs
```
$ python3 -q -X faulthandler segfault.py
```

### command for running python in gdb
```
$ gdb --args /usr/bin/python3.9 segfault.py
$ gdb --args /usr/bin/python3.9 -m pdb segfault.py
```
or -ex r for running on start
```
$ gdb -ex r --args /usr/bin/python3.9 segfault.py
$ gdb -ex r --args /usr/bin/python3.9 -m pdb segfault.py
```

### debugging commands for python in gdb
- stack trace of c stuff?
```
(gdb) bt
```
- get stack trace of python code
```
(gdb) py-bt
```
- get information about all threads
```
(gdb) info threads
```
- see where current thread is in code
```
(gdb) py-list
```
- see where all threads are currently in code
```
(gdb) thread apply all py-list
```

### example debugging
- load script into gdb
```
$ gdb --args /usr/bin/python3.9 segfault.py
```
- run script in gdb
```
(gdb) r
Starting program: /usr/bin/python3 segfault.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff48da700 (LWP 13833)]
[New Thread 0x7fffec0d9700 (LWP 13834)]
[New Thread 0x7fffeb8d8700 (LWP 13835)]
[New Thread 0x7fffe30d7700 (LWP 13836)]
[New Thread 0x7fffda8d6700 (LWP 13837)]
[New Thread 0x7fffca0d5700 (LWP 13838)]
[New Thread 0x7fffc18d4700 (LWP 13839)]
call, /home/robert/repos/exploits/python_code/segfault.py:42
line, /home/robert/repos/exploits/python_code/segfault.py:43
call, /home/robert/repos/exploits/python_code/segfault.py:25
line, /home/robert/repos/exploits/python_code/segfault.py:26
call, /usr/lib/python3.9/ctypes/__init__.py:513
line, /usr/lib/python3.9/ctypes/__init__.py:517

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
```
- get backtrace of program
```
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff77ef8bb in string_at (ptr=0x0, size=-1) at ./Modules/_ctypes/_ctypes.c:5583
#2  0x00007ffff7fbfd1d in ?? () from /lib/x86_64-linux-gnu/libffi.so.7
[...]
```
- select frame for further investigation
```
(gdb) frame 1
#1  0x00007ffff77ef8bb in string_at (ptr=0x0, size=-1) at ./Modules/_ctypes/_ctypes.c:5583
5583    ./Modules/_ctypes/_ctypes.c: No such file or directory.
```
```
(gdb) list
5578    in ./Modules/_ctypes/_ctypes.c
```
- print info about method where seg fault happens
```
(gdb) p string_at
$1 = {PyObject *(const char *, int)} 0x7ffff77ef884 <string_at>
```
- get layout
```
(gdb) layout asm
[...]
|   0x7ffff77ef8b3 <string_at+47>   mov    %rbp %rdi
│   0x7ffff77ef8b6 <string_at+50>   call   0x7ffff77e8290 <strlen@plt>
│  >0x7ffff77ef8bb <string_at+55>   mov    %rax,%rsi
│   0x7ffff77ef8be <string_at+58>   pop    %rcx  
[...]
```
- get info about shared libs
```
(gdb) info sharedlibrary
```
- disassemble function where program crashed
```
(gdb) disas
Dump of assembler code for function string_at:
   0x00007ffff77ef884 <+0>:     push   %rbp
   0x00007ffff77ef885 <+1>:     mov    %rdi,%rbp
   0x00007ffff77ef888 <+4>:     mov    %esi,%ecx
   0x00007ffff77ef88a <+6>:     mov    %rdi,%rdx
   0x00007ffff77ef88d <+9>:     push   %rbx
   0x00007ffff77ef88e <+10>:    xor    %eax,%eax
   0x00007ffff77ef890 <+12>:    mov    %esi,%ebx
   0x00007ffff77ef892 <+14>:    lea    0xb7ca(%rip),%rdi        # 0x7ffff77fb063
   0x00007ffff77ef899 <+21>:    push   %r8
   0x00007ffff77ef89b <+23>:    lea    0xb7be(%rip),%rsi        # 0x7ffff77fb060
   0x00007ffff77ef8a2 <+30>:    call   0x7ffff77e86a0 <PySys_Audit@plt>
   0x00007ffff77ef8a7 <+35>:    test   %eax,%eax
   0x00007ffff77ef8a9 <+37>:    js     0x7ffff77ef8c9 <string_at+69>
   0x00007ffff77ef8ab <+39>:    movslq %ebx,%rsi
   0x00007ffff77ef8ae <+42>:    cmp    $0xffffffff,%ebx
   0x00007ffff77ef8b1 <+45>:    jne    0x7ffff77ef8be <string_at+58>
   0x00007ffff77ef8b3 <+47>:    mov    %rbp,%rdi
   0x00007ffff77ef8b6 <+50>:    call   0x7ffff77e8290 <strlen@plt>
=> 0x00007ffff77ef8bb <+55>:    mov    %rax,%rsi
   0x00007ffff77ef8be <+58>:    pop    %rcx
   0x00007ffff77ef8bf <+59>:    mov    %rbp,%rdi
   0x00007ffff77ef8c2 <+62>:    pop    %rbx
   0x00007ffff77ef8c3 <+63>:    pop    %rbp
   0x00007ffff77ef8c4 <+64>:    jmp    0x7ffff77e81c0 <PyBytes_FromStringAndSize@plt>
   0x00007ffff77ef8c9 <+69>:    pop    %rdx
   0x00007ffff77ef8ca <+70>:    xor    %eax,%eax
   0x00007ffff77ef8cc <+72>:    pop    %rbx
   0x00007ffff77ef8cd <+73>:    pop    %rbp
   0x00007ffff77ef8ce <+74>:    ret    
End of assembler dump.
```

### deubg c extension in python code via gdb
- launch python3 in gdb
```
$ gdb python3
```
- set breakpoint in c function
```
(gdb) break string_at
```
- run python code
```
(gdb) run -m segfault.py
Starting program: /usr/bin/python3 -m segfault.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff489a700 (LWP 16213)]
[New Thread 0x7ffff4099700 (LWP 16214)]
[New Thread 0x7fffeb898700 (LWP 16215)]
[New Thread 0x7fffdb097700 (LWP 16216)]
[New Thread 0x7fffd2896700 (LWP 16217)]
[New Thread 0x7fffca095700 (LWP 16218)]
[New Thread 0x7fffc1894700 (LWP 16219)]
call, /home/robert/repos/exploits/python_code/segfault.py:42
line, /home/robert/repos/exploits/python_code/segfault.py:43
call, /home/robert/repos/exploits/python_code/segfault.py:25
line, /home/robert/repos/exploits/python_code/segfault.py:26
call, /usr/lib/python3.9/ctypes/__init__.py:513
line, /usr/lib/python3.9/ctypes/__init__.py:517

Thread 1 "python3" hit Breakpoint 1, string_at (ptr=0x0, size=-1)
    at ./Modules/_ctypes/_ctypes.c:5579
5579    ./Modules/_ctypes/_ctypes.c: No such file or directory.
```
- hit cont to step into next breakpoint or run program until crash/finish
```
(gdb) cont
```
- hit disas to dissamble last function
```
(gdb) disas
```